"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Project root directory
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================================
# SECURITY & ENVIRONMENT
# ============================================================================

# Secret key for cryptographic signing (sessions, CSRF tokens)
SECRET_KEY = 'django-insecure-0))qam6ln-8zmn2iwba!xx=9#x)u%cw_xm-o!m=!r^tie2$e_='

# Debug mode - shows detailed error pages (disable in production)
DEBUG = True

# Allowed hostnames (empty = localhost only)
ALLOWED_HOSTS = []


# ============================================================================
# INSTALLED APPLICATIONS & MIDDLEWARE
# ============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    "rest_framework",       # REST API framework
    "corsheaders",          # Cross-origin requests for frontend

    "organizations",        # Multi-tenancy (Tenant model)
    "ingestion",           # Data import pipeline
    "activities",          # Core emissions data
    "audit",              # Change tracking
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",  # Must be after SecurityMiddleware
]

# Allow all origins (development only - restrict in production)
CORS_ALLOW_ALL_ORIGINS = True

# Root URL configuration
ROOT_URLCONF = 'config.urls'


# ============================================================================
# TEMPLATES & DATABASE
# ============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# SQLite for development (use PostgreSQL in production)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================================================================
# PASSWORD VALIDATION & LOCALIZATION
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JS, images)
STATIC_URL = 'static/'
