# Generated by Django 6.0.5 on 2026-05-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=30)),
                ('activity_type', models.CharField(choices=[('fuel', 'Fuel'), ('procurement', 'Procurement'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground Transport'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity_original', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_original', models.CharField(blank=True, max_length=50)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('suspicious', 'Suspicious'), ('invalid', 'Invalid'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='valid', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activity_records', to=settings.AUTH_USER_MODEL)),
                ('raw_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_record', to='ingestion.rawactivityrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='activities.activityrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
            ],
        ),
    ]
